---
- name: Install Vector | prepare architecture name when x64
  ansible.builtin.set_fact:
    architecture_name: amd64
  when: ansible_architecture == 'x86_64'
- name: Install Vector | prepare architecture name when else
  ansible.builtin.set_fact:
    architecture_name: undefined
  when: ansible_architecture != 'x86_64'
- name: Install Vector | DEB install
  become: true
  ansible.builtin.apt:
    deb: https://packages.timber.io/vector/0.9.1/vector-amd64.deb
  notify: restart vector service